### ISSUE TITLE
Error: Cannot find module 'protractor-multiple-cucumber-html-reporter-plugin'

### ISSUE THREAD

**Issue by edgarechm** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#15]
When I run my tests, I get this Error: Cannot find module 'protractor-multiple-cucumber-html-reporter-plugin' I've double checked and protractor-multiple-cucumber-html-reporter-plugin is present in my node-modules folder. I already ran the install several times, also by deleting the node-modules directory completely.

Node Version: v9.3.0
Npm Version: 6.0.1
Protractor Version: Version 5.1.1
protractor-multiple-cucumber-html-reporter-plugin Version: 1.7.0
install protractor-cucumber Version: 0.1.8
install protractor-cucumber-framework Version: 5.0.0
install cucumber Version: 4.2.1

**Here's my full config file:**

```
exports.config = {
        directConnect: true,
	rootElement: 'html',
	chromeDriver: '/srv/build/applications/chromedriver/chromedriver_win32/chromedriver.exe',
	seleniumServerJar: './node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone.jar',
	resultJsonOutputFile:'',
	getPageTimeout: 60000,
	allScriptsTimeout: 60000,
	framework: 'custom',
	frameworkPath: require.resolve('protractor-cucumber-framework'),
	capabilities: {
		shardTestFiles: true,
		maxInstances: 5,
		'browserName': 'chrome',
		chromeOptions:{
		  args:["--headless"]
		},
	},
	
	onPrepare: function(){
		browser.ignoreSynchronization=true;
		global.EC = protractor.ExpectedConditions;
	},
	specs: [featsLocation + '*.feature'],
	baseUrl: '',
	plugins: [{
		package: 'protractor-multiple-cucumber-html-reporter-plugin',
		options:{
			jsonDir: './report',
			jsonOutputPath:'./report',
			reportPath:'./',
	        	automaticallyGenerateReport: true,
	        	openReportInBrowser: true,
	        	saveCollectedJSON: true,
	        	disableLog: true,
	        	displayDuration: true,
	        	removeOriginalJsonReportFile: true,
	                removeExistingJsonReportFile: true
		}
	}],

	cucumberOpts: {
		tags: 'not @ignore and (@rt)',
		require: [stepsLocation + '*.spec.js'],
		monochrome: true,
		strict: true,
		format: 'json:./report/results.json'
	},
};
```

Here is the error as it displays on my console log:

```
[phantomjs #01-3] module.js:472
[phantomjs #01-3]     throw err;
[phantomjs #01-3]     ^
[phantomjs #01-3] 
[phantomjs #01-3] Error: Cannot find module 'protractor-multiple-cucumber-html-reporter-plugin'
[phantomjs #01-3]     at Function.Module._resolveFilename (module.js:470:15)
[phantomjs #01-3]     at Function.Module._load (module.js:418:25)
[phantomjs #01-3]     at Module.require (module.js:498:17)
[phantomjs #01-3]     at require (internal/module.js:20:19)
[phantomjs #01-3]     at /usr/lib/node_modules/protractor/built/plugins.js:51:33
[phantomjs #01-3]     at Array.forEach (native)
[phantomjs #01-3]     at new Plugins (/usr/lib/node_modules/protractor/built/plugins.js:38:28)
[phantomjs #01-3]     at Runner.run (/usr/lib/node_modules/protractor/built/runner.js:264:39)
[phantomjs #01-3]     at process.<anonymous> (/usr/lib/node_modules/protractor/built/runnerCli.js:42:20)
[phantomjs #01-3]     at emitTwo (events.js:106:13)

[12:21:25] I/testLogger - 

[12:21:25] E/launcher - Runner process exited unexpectedly with error code: 1
```
... and here is a listing of the plugin directory, showing that IT IS installed:

```
$ ls -la ./node_modules/protractor-multiple-cucumber-html-reporter-plugin
total 121
drwxr-xr-x 1 edgarechm 1049089     0 Jun 14 17:58 ./
drwxr-xr-x 1 edgarechm 1049089     0 Jun 14 17:59 ../
-rw-r--r-- 1 edgarechm 1049089  6566 Apr 15 00:19 .eslintrc.json
-rw-r--r-- 1 edgarechm 1049089   608 Sep 11  2017 .travis.yml
-rw-r--r-- 1 edgarechm 1049089  4741 Apr 15 00:21 CHANGELOG.md
-rw-r--r-- 1 edgarechm 1049089  3403 Sep 11  2017 CONTRIBUTING.md
-rw-r--r-- 1 edgarechm 1049089 11608 Apr 15 00:25 index.js
drwxr-xr-x 1 edgarechm 1049089     0 Jun 14 17:58 json-output-path/
-rw-r--r-- 1 edgarechm 1049089  1070 Sep 11  2017 LICENSE
-rw-r--r-- 1 edgarechm 1049089  2626 Jun 14 17:58 package.json
-rw-r--r-- 1 edgarechm 1049089 16988 Apr 15 00:23 README.md
drwxr-xr-x 1 edgarechm 1049089     0 Jun 14 17:58 report-path/
```

**Comment by Coregraph** [comment]
I have the same issue this week, I solved it with:
       `package: require.resolve('protractor-multiple-cucumber-html-reporter-plugin')` 
in the plugins declaration.

**Comment by edgarechm** [comment]
Thanks that worked.

I also figured out, that the problem is a broken package.json. So, "npm init" also solves the issue.

So there are two solutions to the issue:
1) What @Coregraph  suggested, helped me when I placed my code in our "VCS", because we don't keep "package.json" on version control.
2) Create a new package.json using either "npm init" and answer mandatory questions or use "npm init -y" and skip all questions.

**Comment by wswebcreation** [comment]
@edgarechm 

What do you mean with 

> Create a new package.json using either "npm init" and answer mandatory questions or use "npm init -y" and skip all questions.

Is my `package.json` not correct?

**Comment by edgarechm** [comment]
Hi Wim,

I'm sorry, I had the bad package.json. I updated my comment to clarify.

Thanks!

**Comment by wswebcreation** [comment]
@edgarechm 

Tnx for the feedback. Hope you like the module and the report 😉

**Comment by as842718** [comment]
@wswebcreation  after fix above issue. I'm getting this 

![image](https://user-images.githubusercontent.com/25057113/45253381-cf037c80-b383-11e8-9c8e-1be39b03c44f.png)

Can you please help me in this.

**Comment by wswebcreation** [comment]
@as842718 
Can you please create a new issue and provide all the relevant info to it?

**Comment by as842718** [comment]
yeah sure
