### ISSUE TITLE
Running it against a remote selenium grid makes the plugin fail.

### ISSUE THREAD

**Issue by jgarces-tw** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#9]
When running the plugin against an external selenium grid the following error happens:
```
15:38:25] I/plugins -           Fail:  protractor-multiple-cucumber-html-reporter-plugin Runtime 
[15:38:25] E/plugins -          Failure during postResults: Cannot read property 'toLowerCase' of undefined
[15:38:25] E/plugins -          TypeError: Cannot read property 'toLowerCase' of undefined
                    at eval (lodash.templateSources[1]:100:62)
                    at arrayEach (/protractor-e2e/node_modules/lodash/lodash.js:537:11)
                    at Function.forEach (/protractor-e2e/node_modules/lodash/lodash.js:9359:14)
                    at eval (lodash.templateSources[1]:34:4)
                    at _createFeaturesOverviewIndexPage (/protractor-e2e/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:390:92)
                    at Object.generateReport [as generate] (/protractor-e2e/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:119:5)
                    at Object.postResults (/protractor-e2e/node_modules/protractor-multiple-cucumber-html-reporter-plugin/index.js:251:43)
                    at resolver (/protractor-e2e/node_modules/protractor/built/plugins.js:194:51)
                    at Function.promise (/protractor-e2e/node_modules/q/q.js:682:9)
                    at Plugins.safeCallPluginFun (/protractor-e2e/node_modules/protractor/built/plugins.js:207:22)
                    at promises.pluginObjs.filter.map.pluginObj (/protractor-e2e/node_modules/protractor/built/plugins.js:219:40)
                    at Array.map (native)
                    at Plugins.postResults (/protractor-e2e/node_modules/protractor/built/plugins.js:219:18)
                    at q.then.then.then.then.then.then.then.then (/protractor-e2e/node_modules/protractor/built/runner.js:432:28)
                    at _fulfilled (/protractor-e2e/node_modules/q/q.js:834:54)
                    at self.promiseDispatch.done (/protractor-e2e/node_modules/q/q.js:863:30)
```

if the tests are however run with direct connection (direct driver) against a local machine this does not happen. I did not test with a local selenium grid.

**Comment by wswebcreation** [comment]
This error means that you are missing some metadata about browser and so on. Did you implement [this](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#metadata)?

Can you also provide you complete config?

**Comment by jgarces-tw** [comment]
Thanks for the tip! apparently platform: { name: undefined } makes it crash and setting it makes it work.
